django/accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'   #for namespace

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signout/', views.SignoutView.as_view(), name='signout'),
]

django/imgdesc/urls.py
from django.urls import path
from . import views



app_name = 'imgdesc'

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('list/', views.ListView.as_view(), name='list'),
    path('list/ajax/<int:pk>/', views.ListajaxView, name='listajax'),
    path('<int:pk>/<mode>/', views.BoardView.as_view(), name='board'),
    path('voice/<int:pk>', views.tts.as_view(), name='tts'),
]

django/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import imgdesc.views
#import accounts.views      #나중에 필요하면 써

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', imgdesc.views.IndexView.as_view(), name='index'),
#    path('index', IndexView.as_view()),
#    path('home/', IndexView.as_view()),

    path('imgdesc/', include('imgdesc.urls')),
    path('accounts/', include('accounts.urls')),
]

from django.conf.urls.static import static
from django.conf import settings
#개발환경에서의 media 파일 서빙
#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/imgdesc/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

from django.utils import timezone
#from django.conf import settings
from django.contrib.auth.models import User

#for delete
import os
from django.conf import settings

class ImgdescDB(models.Model):
    img_no = models.AutoField(primary_key=True, blank=True)
    userid = models.ForeignKey(User, models.DO_NOTHING, db_column='userID')  # Field name made lowercase.
#    userid = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING) #이걸로하면 column선택 못해서..우선위에로
    photo = models.ImageField(upload_to="%Y%m/%d", null=False)
    caption_en = models.CharField(max_length=200, blank=True, null=True)
    caption_ko = models.CharField(max_length=200, blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    audio_url = models.CharField(max_length=200, blank=True, null=True)

    def _str__(self):   #객체의 문자열 표현 메소드
        return self.caption_en

    def total_myphoto(self):
        return self.img_no.count()

'''
    # Delete overwriting 하면 파일이 ImgdescDB 객체 인스턴스와 함께 삭제될 것이다.
    def delete(self, *args, **kwargs):
        try:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.photo.path))
            super(ImgdescDB, self).delete(*args, **kargs)   #원래의 delete 함수를 실행
'''
#    class Meta:
#        db_table = 'imgdesc_list'  #setting the db name. default value: myapp_modelName

django/imgdesc/forms.py
from django import forms
from .models import ImgdescDB

def validator(value):
    if value.split('.')[-1] not in ['jpg','jpeg','png','bmp'] :
        raise ValidationError("jpg, jpeg, png, bmp 그림 파일을 지원합니다.");


class PostForm(forms.ModelForm):
    #    title = CharField(label='제목', max_length=20, validators=[validator])
    #    text = CharField(label='내용', widget=Textarea)
    class Meta:
        model = ImgdescDB    #model은 쟝고가 정의한 것. 에다 model data를 넣어준다
        fields = ['photo']      #가져올 fields만 선택 가능하다. 'created_date','userid',
#        fields = '__all__'

    def __init__(self, *args, **kwargs):                    #내 생성자 정의
        super(PostForm, self).__init__(*args, **kwargs)     #부모 생성자 호출
        self.fields['photo'].validuserIDators = [validator]

django/imgdesc/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import ImgdescDB

from django.views import View
from django.views import generic
from django.http import HttpResponse

from django.forms import Form, CharField, Textarea, ValidationError
from .forms import PostForm

from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

# captioning
import os, sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../captioning/')))
from test_oneimg import run_captioning, testimport, translation


# Create your views here.
class IndexView(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        mydb = ImgdescDB.objects.all()
        print(mydb)

        template_name = 'imgdesc/index.html'
        return render(request, template_name, {'user': request.user, 'mydb': mydb})


class ListView(LoginRequiredMixin, generic.TemplateView):
    def get(self, request, *args, **kwargs):
        #        username = request.session['username']  # text
        #        user = User.objects.get(username=username)  # object
        #        mydb = ImgdescDB.objects.all().filter(userid=request.user)
        mydb = ImgdescDB.objects.filter(userid=request.user).all().order_by('-img_no')
        # pagination
        page = request.GET.get('page', 1)
        p = Paginator(mydb, 10)  # collection 형태의 데이터면 상관 없다 / page 당 개수
        mydb_sub = p.page(page)

        #        ImgdescDB.objects.create()
        #        print(mydb.photo.url)

        return render(request, 'imgdesc/list.html', {'mydb': mydb_sub})  # 리턴에 'user': request.user 지움.for templatetags
        # return render(request, "imgdesc/list.html", {'username': username, 'mydb': mydb})



class tts(View):
    def post(self, request, pk):
#        user = request.user  # 로그인한 유저를 가져온다.
#        img_no = request.POST.get('pk', None)
        img_no = pk
        mypost = ImgdescDB.objects.get(pk=img_no)  # 해당 오브젝트를 가져온다.

        # tts
        from gtts import gTTS
        tts = gTTS(text=mypost.caption_ko, lang='ko')
        myvoicepath = os.path.splitext(mypost.photo.path)[0] + '.mp3'
        myvoicepath = myvoicepath.replace('\\','/')
        tts.save(myvoicepath)
        message = '음성 생성 중입니다. 새로고침해주세요'
        #DB저장
        myvoiceurl = '/media/' + myvoicepath.split('media/')[-1]
        mypost.audio_url = myvoiceurl
        mypost.save()
        context = {'myvoiceurl': myvoiceurl, 'message': message}
        return JsonResponse(context)
        # dic 형식을 json 형식으로 바꾸어 전달한다.


class ListajaxView():
    def get(self, request, pk):
        mydb = get_object_or_404(ImgdescDB, pk=pk)
        voice_filename = mydb.photo.split('.')[:-1]
        voice_filename = "".join(voice_filename) + '.mp3'
        data = {
            'img_no': mydb.img_no,
            'cap_txt': mydb.caption_ko,
            'voice': voice_filename,
        }
        return JsonResponse({'data': data})

    def post(self, request):
        if self.request.is_ajax():
            mydb = ImgdescDB.objects.all()
            text = self.request.POST['message']
            return JsonResponse({})


class BoardView(LoginRequiredMixin, View):
    #    login_url = '/accounts/signin/'
    def get(self, request, pk, mode):  # 특정 포스트를 수정하므로 pk parameter를 받아와야 한다.
        if mode == 'detail':
            p = get_object_or_404(ImgdescDB, pk=pk)  # 에러나면 아래 return이 아닌, pagenotfound(404) exception로 리턴시킨다.
            return render(request, "imgdesc/detail.html", {"d": p})
        elif mode == 'add':
            form = PostForm()  # empty form
            return render(request, "imgdesc/edit.html", {'form': form})
        elif mode == 'edit':
            post = get_object_or_404(ImgdescDB, pk=pk)
            form = PostForm(instance=post)  # instance라는 parameter에 model data(post) 넣음
            return render(request, "imgdesc/edit.html", {'form': form})
        elif mode == 'del':
            post = get_object_or_404(ImgdescDB, pk=pk)
            post.delete()
            return redirect('/imgdesc/list')
        else:
            return HttpResponse("error page")

    def post(self, request, pk, mode='edit'):
        #        username = request.session["username"]
        #       userid = User.objects.get(username=username)

        # 글쓰기에서 submit 시
        if pk == 0:
            author = ImgdescDB.objects.create(userid=request.user)  # user id는 폼 이전에 미리 채움. NOT NULL이라서
            form = PostForm(request.POST, request.FILES, instance=author)  # 받은 데이터로 폼 채움



        # 수정에서 submit 시
        else:
            post = get_object_or_404(ImgdescDB, pk=pk)
            form = PostForm(request.POST, request.FILES, instance=post)

        # 폼 유효성 검사
        if form.is_valid():
            post = form.save(commit=False)

            if pk == 0:  # 글쓰기 시
                pho = request.FILES.get('photo')
                uploaded_image = ImgdescDB(photo=pho)

                import datetime
                today = datetime.date.today()
                myphotodir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                          'media/') + '{:%Y%m/%d/}'.format(today)
                myphotourl = myphotodir + uploaded_image.photo.url.split('/')[-1]
                captioning_result = run_captioning(myphotourl)
                captioning_result_ko = translation(captioning_result)
                #                captioning_result = testimport('testing')
                post.caption_en = captioning_result
                post.caption_ko = captioning_result_ko

                #                post.userid = request.user      #유효성 한 다음에 다시 user 넣는건가.. 위와 중복이라 뺌.
                post.save()  # form data로부터 post data(model data)를 얻기 위해서 save. NOT for save.
                '''
                # tts
                from gtts import gTTS
                tts = gTTS(text=captioning_result_ko, lang='ko')
                myvoiceurl = os.path.splitext(myphotourl)[0] + '.mp3'
                tts.save(myvoiceurl)
                '''

            else:
                post.publish()
            return redirect('/imgdesc/list')
#            return JsonResponse({'status': 0, 'message': 'Uploaded Successfully'})

        else:
            return render(request, 'imgdesc/edit.html', {'form':form})
#            return JsonResponse({'status': -1, 'message': 'Failed', 'errors': form.errors})



def ajaxdel(request):
    pk = request.GET.get('pk')
    post = ImgdescDB.objects.get(pk=pk)
    post.delete()
    return JsonResponse({'error': '0'})


def ajaxget(request):
    username = request.session["username"]
    user = User.objects.get(username=username)

    page = request.GET.get('page', 1)
    datas = ImgdescDB.objects.all().filter(useid=user, category='common')

    page = int(page)
    subs = datas[(page - 1) * 3:(page) * 3]
    '''p = Paginator(datas, 3)
    subs = p.page(page)'''

    datas = {'mydb': [{'pk': sub.pk, 'title': sub.title, 'cnt': sub.cnt} for sub in subs]}
    return JsonResponse(datas, json_dumps_params={'ensure_ascii': False})
    # 마지막 JsonResponse 뒤에 옵션은, json만 출력했을 때 한글이 제대로 보이도록 하는 옵션이다.
    # 자바스크립트가 알아서 인코딩하므로 없어도 상관 없다.

django/templates/imgdesc/TTSresult.html
{{ myvoiceurl }}
                          <audio controls>
                            <source src="{{ myvoiceurl }}" type="audio/mp3">
                          </audio>

django/templates/imgdesc/edit.html
{% extends 'imgdesc/header.html' %}
{% block title %}IMAGE TO TXT - 작성{% endblock %}
{% block content %}


<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Add</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">




<form method="post" enctype="multipart/form-data" id="ajax_upload_form">
{% csrf_token %}
    <div class="form-group">
      {{ form.as_p }}
      {% if form.photo.value %}
      {% else %}<!--신규일 때-->
      <small id="fileHelp" class="form-text text-muted">jpg, jpeg, png, bmp 그림 파일을 지원합니다.</small>
      {% endif %}
    </div>
    <input type="submit" class="btn btn-primary btn-xl js-scroll-trigger" value="Upload">
</form>


                    </p>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block js-foot %}
   <script type="text/javascript">
    // form upload
    $('#ajax_upload_form').submit(function(e){
        //preventDefault 는 기본으로 정의된 이벤트를 작동하지 못하게 하는 메서드이다. submit을 막음
        e.preventDefault();
        // Get form
        $form = $(this);
        // Create an FormData object
        var formData = new FormData(this);
        // disabled the submit button
        $("#btnSubmit").prop("disabled",true);

        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: formData,
            timeout: 600000,
            success: function (response) {
                console.log(response);
                if(response.status == -1){
                    console.log("ERROR : ", error);
                    $("#btnSubmit").prop("disabled",false);
                    alert(response.message);
                    $form.find('[name=' + name + ']').after(error);
                    })
                }
                else{
                    alert(response.message);
                    $("#btnSubmit").prop("disabled",false);
                    window.location = "/imgdesc/list";
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });
    // end
   </script>
{% endblock js-foot %}

django/templates/imgdesc/footer.html
    <!-- Footer-->
    <footer class="bg-light py-5">
      <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Start Bootstrap</div></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Core theme JS-->
    <script type="text/javascript" type="text/javascript" src="{% static 'imgdesc/js/start_creativegh.js' %}"></script>
{% block js-foot %}{% endblock js-foot %}
</body></html>

django/templates/imgdesc/header.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
    <meta name="description" content="">
    <meta name="author" content="">
<!--    <link rel="icon" href="../../favicon.ico">-->
    <title>{% block title %}{% endblock %}</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- Third party plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'imgdesc/css/start_creativegh.css' %}" rel="stylesheet">

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <body id="page-top">
      <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="#page-top">Oculus</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'index' %}">Home</a></li>
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'imgdesc:list' %}">List</a></li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:signout'%}">{% firstof user.username %} Logout</a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:signin'%}">Login</a></li>
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'accounts:signup'%}">Register</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>


{% block content %}
{% endblock %}


    <!-- Footer-->
    <footer class="bg-light py-5">
      <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Start Bootstrap</div></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Core theme JS-->
    <script type="text/javascript" type="text/javascript" src="{% static 'imgdesc/js/start_creativegh.js' %}"></script>
{% block js-foot %}{% endblock js-foot %}
</body></html>

django/templates/imgdesc/index.html
{% extends 'imgdesc/header.html' %}
{% block title %}IMAGE TO TXT - 환영합니다.{% endblock %}

Here is index. 여긴 안 나오지롱
{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">이미지를 텍스트로</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">이미지를 업로드해보세요. 사진을 설명해드립니다!</p>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'imgdesc:list' %}">시작하기</a>
            </div>
        </div>
    </div>
</header>
<!-- About-->
<section class="page-section bg-primary" id="about">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="text-white mt-0">OCULUS: Image to Text</h2>
                <hr class="divider light my-4" />
                <p class="text-white-50 mb-4">We'll descript your Image. Just upload your Image</p>
                <a class="btn btn-light btn-xl js-scroll-trigger" href="{% url 'imgdesc:list' %}">LEGO!!</a>
            </div>
        </div>
    </div>
</section>





{% endblock %}

django/templates/imgdesc/list.html
{% extends 'imgdesc/header.html' %}
{% block title %}IMAGE TO TXT - 리스트{% endblock %}
{% block content %}



<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">List</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-10 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">


                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'imgdesc:board' pk=0 mode='add' %}">Upload</a>

                  <!--navigation-->
                  {% if mydb.has_other_pages %}
                  <div>
                    <ul class="pagination">

                      <li class="page-item {% if not mydb.has_previous %}disabled{% endif %}">
                        <a class="page-link" {% if mydb.has_previous %}href="?page={{ mydb.previous_page_number }}"{% endif %}>&laquo;</a>
                      </li>
                      {% for i in mydb.paginator.page_range %}
                      <li class="page-item {% if mydb.number == i %}active{% endif %}">
                        <a class="page-link" {% if not mydb.number == i %}href="?page={{ i }}"{% endif %}>{{ i }}</a>
                      </li>
                      {% endfor %}
                      <li class="page-item {% if not mydb.has_next %}disabled{% endif %}">
                        <a class="page-link" {% if mydb.has_next %}href="?page={{ mydb.next_page_number }}"{% endif %}>&raquo;</a>
                      </li>
                    </ul>
                  </div>
                  {% endif %}

                  <br/><br/>

                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">no</th>
                        <th scope="col">image</th>
                        <th scope="col">caption</th>
                        <th scope="col">voice</th>
                        <th scope="col">created_date</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for lst in mydb %}
                      <tr class="table-light">
                        <td>{{ forloop.counter }}</td>
                        <td>
                          {% if lst.photo %}
                            <img src="{{ lst.photo.url }}" width="100px" alt=""></td>
                          {% endif %}
                        </td>
                        <td id="{{ lst.img_no }}_cap_txt">{{ lst.caption_ko }}</td>
                        <td id="{{ lst.img_no }}_voice">
                          <input type="button" class="tts btn btn-primary" name="{{ lst.img_no }}" value="음성 생성">
                          {% if lst.audio_url %}
                          <audio controls>
                            <source id="{{ lst.img_no }}_audio" src="{{ lst.audio_url }}" type="audio/mp3">
                          </audio>
                          {% endif %}

                        </td>
                        <td>{{ lst.created_date }}</td>
                        <td><span class="control hidden">
                          <a href="{% url 'imgdesc:board' pk=lst.pk mode='del' %}" onclick="return confirm('정말 삭제하시겠습니까?')">
                            Del</a></td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>



                </p>
            </div>
        </div>
    </div>
</header>







{% endblock %}

{% block js-foot %}



<script type="text/javascript">
// 버튼 클릭 > ajax통신 (like url로 전달) > views의 like 메소드에서 리턴하는 값 전달받기 > 성공시 콜백 호출
$('.tts').click(function(){
  var pk = $(this).attr('name') // 클릭한 요소의 attribute 중 name의 값을 가져온다.
  $.ajax({
      type: "POST", // 데이터를 전송하는 방법을 지정한다.
      url: "/imgdesc/voice/"+pk, // 통신할 url을 지정한다.
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터를 전송할 때 이 옵션을 사용한다.
      dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정한다. 없으면 알아서 판단한다.
      // 서버측에서 전송한 데이터 views.py like 메소드
      // context = {'likes_count' : memo.total_likes, 'message' : message}
      // json.dump(context)를 통해서 json 형식으로 전달된다.

      success: function(response){ // 성공했을 때 호출할 콜백을 지정한다.
        id = $(this).attr('name')
        $('#' + pk + 'voice').html("<audio controls><source id=\'"+id+"_audio\' src=\'"+response.myvoiceurl+"\' type=\'audio/mp3\'></audio>");
        alert(response.message);
      },
      error:function(request,status,error){
        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      }
  });
})
</script>


{% endblock js-foot %}